<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Module'                        => __DIR__ . '/Application/Module.php',
    'Application\Controller\IndexController'    => __DIR__ . '/Application/src/Application/Controller/IndexController.php',
    'Market\Module'                             => __DIR__ . '/Market/Module.php',
    'Market\Controller\IndexController'         => __DIR__ . '/Market/src/Market/Controller/IndexController.php',
    'ZendSkeletonModuleTest\Framework\TestCase' => __DIR__ . '/Market/tests/Market/Framework/TestCase.php',
    'ZendSkeletonModuleTest\SampleTest'         => __DIR__ . '/Market/tests/Market/SampleTest.php',
);
