<style>
    label{
        position: relative;
        display: block;
    }
    
    label span{
        position: relative;
        display: inline-block;
        width: 100px;
    }
    
    input[type=submit]{
        margin-left: 100px;
    }
</style>

<h1>Post Controller</h1>

<?php $this->postForm->prepare(); ?>
<?php echo $this->form()->openTag($this->postForm); ?>
<?php echo $this->formCollection($this->postForm); ?>


<?php echo $this->form()->closeTag($this->postForm); ?>

<?php Zend\Debug\Debug::dump($this->data) ?>
