<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Market\Module'                        => __DIR__ . '/Module.php',
    'Market\Controller\SkeletonController' => __DIR__ . '/src/Market/Controller/SkeletonController.php',
    'ZendSkeletonModuleTest\Framework\TestCase'        => __DIR__ . '/tests/Market/Framework/TestCase.php',
    'ZendSkeletonModuleTest\SampleTest'                => __DIR__ . '/tests/Market/SampleTest.php',
);